<div>
<header class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 class="text-2xl font-bold">Respostas prontas</h1><p class="mt-1 text-sm text-slate-500">Selecione uma categoria ou pesquise diretamente.</p></div><div class="flex flex-wrap gap-2"><button wire:click="openImporter" class="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm font-semibold text-blue-700">Importar Word</button><button wire:click="openCategoryManager" class="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-semibold">Gerenciar categorias</button><button wire:click="createResponse" class="rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white">+ Nova resposta</button></div></header>
@if(session()->has('message'))<div class="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('message') }}</div>@endif
@if(session()->has('error'))<div class="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{{ session('error') }}</div>@endif

@if($showImporter)
<section class="mt-6 rounded-2xl border border-blue-200 bg-white p-5 shadow-sm">
<div class="flex items-start justify-between gap-4"><div><h2 class="text-lg font-semibold">Importar respostas do Word</h2><p class="mt-1 text-sm text-slate-500">O sistema considera como título o texto que estiver simultaneamente em <strong>negrito e sublinhado</strong>. O conteúdo seguinte pertence a esse título até o próximo título encontrado.</p></div><button wire:click="closeImporter" class="rounded-lg border border-slate-300 px-3 py-2 text-sm">Fechar</button></div>
<div class="mt-5 grid gap-4 md:grid-cols-2"><div><label class="text-sm font-medium">Arquivo Word (.docx)</label><input wire:model="wordFile" type="file" accept=".docx" class="mt-1 block w-full rounded-xl border border-slate-300 bg-white p-3 text-sm">@error('wordFile')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div><div><label class="text-sm font-medium">Categoria para as respostas</label><select wire:model="importCategoryId" class="mt-1 w-full rounded-xl border border-slate-300 bg-white px-4 py-3"><option value="">Sem categoria</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->parent ? $category->parent->name.' › ' : '' }}{{ $category->name }}</option>@endforeach</select></div></div>
<div class="mt-4"><button wire:click="previewImport" wire:loading.attr="disabled" class="rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white"><span wire:loading.remove wire:target="previewImport">Analisar arquivo</span><span wire:loading wire:target="previewImport">Analisando...</span></button></div>
@if(count($importPreview))<div class="mt-6"><div class="flex flex-wrap items-center justify-between gap-3"><div><h3 class="font-semibold">Prévia da importação</h3><p class="text-sm text-slate-500">{{ count($importPreview) }} respostas identificadas. Confira antes de gravar no banco.</p></div><button wire:click="confirmImport" wire:confirm="Deseja importar estas {{ count($importPreview) }} respostas?" class="rounded-xl bg-emerald-600 px-5 py-3 text-sm font-semibold text-white">Confirmar importação</button></div><div class="mt-4 max-h-[520px] space-y-3 overflow-y-auto rounded-xl bg-slate-50 p-3">@foreach($importPreview as $item)<article class="rounded-xl border border-slate-200 bg-white p-4"><h4 class="font-semibold">{{ $item['title'] }}</h4><p class="mt-2 whitespace-pre-line text-sm leading-6 text-slate-600">{{ \Illuminate\Support\Str::limit($item['content'],500) }}</p></article>@endforeach</div></div>@endif
</section>
@endif

@if($showCategoryManager)<section class="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex justify-between gap-4"><div><h2 class="text-lg font-semibold">Categorias e subcategorias</h2><p class="text-sm text-slate-500">Organize as respostas em áreas.</p></div><button wire:click="closeCategoryManager" class="rounded-lg border px-3 py-2 text-sm">Fechar</button></div><form wire:submit="saveCategory" class="mt-5 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><div><input wire:model="categoryName" placeholder="Nome da categoria" class="w-full rounded-xl border px-4 py-3">@error('categoryName')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div><select wire:model="parentCategoryId" class="rounded-xl border bg-white px-4 py-3"><option value="">Categoria principal</option>@foreach($categories->whereNull('parent_id') as $category)@if($category->id!==$editingCategoryId)<option value="{{ $category->id }}">{{ $category->name }}</option>@endif @endforeach</select><button class="rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white">{{ $editingCategoryId?'Salvar':'+ Adicionar' }}</button></form><div class="mt-5 divide-y rounded-xl border">@foreach($categories as $category)<div class="flex items-center justify-between gap-3 p-4"><div><span class="font-medium">{{ $category->parent ? $category->parent->name.' › ' : '' }}{{ $category->name }}</span><div class="text-xs text-slate-500">{{ $category->responses_count }} respostas</div></div><div class="flex gap-2"><button wire:click="editCategory({{ $category->id }})" class="rounded-lg border px-3 py-2 text-sm">Editar</button><button wire:click="deleteCategory({{ $category->id }})" wire:confirm="Excluir categoria?" class="rounded-lg border border-red-200 px-3 py-2 text-sm text-red-600">Excluir</button></div></div>@endforeach</div></section>@endif

@if($showForm)<section class="mt-6 rounded-2xl border bg-white p-5"><div class="flex justify-between"><h2 class="text-lg font-semibold">{{ $editingId?'Editar resposta':'Nova resposta' }}</h2><button wire:click="closeForm" class="rounded-lg border px-3 py-2 text-sm">Fechar</button></div><form wire:submit="saveResponse" class="mt-4 grid gap-4"><input wire:model="title" placeholder="Título" class="rounded-xl border px-4 py-3"><div class="grid gap-4 md:grid-cols-2"><select wire:model="formCategoryId" class="rounded-xl border bg-white px-4 py-3"><option value="">Sem categoria</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->parent ? $category->parent->name.' › ' : '' }}{{ $category->name }}</option>@endforeach</select><input wire:model="keywords" placeholder="Palavras-chave" class="rounded-xl border px-4 py-3"></div><textarea wire:model="content" rows="8" placeholder="Resposta" class="rounded-xl border px-4 py-3"></textarea><label class="text-sm"><input wire:model="isFavorite" type="checkbox"> Marcar como favorita</label><button class="justify-self-end rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white">Salvar</button></form></section>@endif

<div class="mt-6"><input wire:model.live.debounce.250ms="search" type="search" placeholder="Buscar por título, conteúdo ou palavra-chave..." class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3.5"></div>
<section class="mt-7"><div class="mb-3 flex justify-between"><h2 class="font-semibold">Categorias</h2><button wire:click="selectCategory(null)" class="rounded-lg border bg-white px-3 py-2 text-sm">Todas</button></div><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@foreach($categories->whereNull('parent_id') as $category)<button wire:click="selectCategory({{ $category->id }})" class="min-h-20 rounded-xl border p-4 text-left {{ $categoryId===$category->id?'border-blue-500 bg-blue-50':'bg-white' }}"><span class="block font-semibold">{{ $category->name }}</span><span class="mt-1 block text-xs text-slate-500">{{ $category->responses_count }} respostas diretas · {{ $categories->where('parent_id',$category->id)->count() }} subcategorias</span></button>@endforeach</div></section>
<section class="mt-8"><div class="mb-3 flex justify-between gap-3"><div><h2 class="font-semibold">{{ $categoryId?optional($categories->firstWhere('id',$categoryId))->name:($favoritesOnly?'Favoritos':'Todas as respostas') }}</h2><p class="text-sm text-slate-500">{{ $responses->count() }} respostas encontradas</p></div><button wire:click="toggleFavorites" class="rounded-lg border bg-white px-3 py-2 text-sm">★ Favoritos</button></div><div class="space-y-3">@forelse($responses as $response)<article class="rounded-xl border bg-white p-5"><div class="flex justify-between gap-4"><div class="min-w-0 flex-1">@if($response->category)<div class="text-xs text-slate-500">{{ $response->category->parent ? $response->category->parent->name.' › ' : '' }}{{ $response->category->name }}</div>@endif<h3 class="mt-1 text-lg font-semibold">{{ $response->title }}</h3><div class="mt-3 whitespace-pre-line text-sm leading-6 text-slate-600">{{ $response->content }}</div></div><button wire:click="toggleFavorite({{ $response->id }})" class="h-11 w-11 rounded-lg border">{{ $response->is_favorite?'★':'☆' }}</button></div><div class="mt-4 flex gap-2"><button type="button" x-data x-on:click="navigator.clipboard.writeText(@js($response->content));$el.textContent='Copiado!';setTimeout(()=>$el.textContent='Copiar resposta',1200)" class="rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Copiar resposta</button><button wire:click="editResponse({{ $response->id }})" class="rounded-lg border px-4 py-2.5 text-sm">Editar</button><button wire:click="deleteResponse({{ $response->id }})" wire:confirm="Excluir esta resposta?" class="rounded-lg border border-red-200 px-4 py-2.5 text-sm text-red-600">Excluir</button></div></article>@empty<div class="rounded-xl border border-dashed bg-white p-8 text-center text-sm text-slate-500">Nenhuma resposta encontrada.</div>@endforelse</div></section>
</div>