import { useEffect, useMemo, useState } from 'react'
import { Search, LayoutDashboard, MessageSquareText, FolderTree, Star, Upload, Settings, Plus, Copy, Eye, Pencil, Menu, X, ChevronRight, Trash2, Save } from 'lucide-react'

const seed=[
{id:1,title:'Chamado de venda SGS',category:'Comercial › SGS',content:'Prezados, boa tarde.\n\nSegue abaixo o modelo de resposta para abertura do chamado de venda SGS. Confira os dados do cliente antes do envio.',tags:['sgs','venda','chamado'],favorite:false},
{id:2,title:'Cancelamento PCLAB ONLINE',category:'PCLAB Online › Cancelamento',content:'Prezado(a), boa tarde.\n\nRecebemos sua solicitação de cancelamento. Seguem as orientações necessárias para prosseguirmos com o atendimento.',tags:['pclab','cancelamento'],favorite:true},
{id:3,title:'Resposta integração de sistemas: API',category:'Integrações › API',content:'Prezado(a), boa tarde.\n\nPara integração via API, é necessário validar os dados de acesso e os endpoints disponíveis para o serviço contratado.',tags:['api','integração'],favorite:false}
]
const seedCats=['Comercial › SGS','PCLAB Online › Cancelamento','Integrações › API']
const nav=[[LayoutDashboard,'Início'],[MessageSquareText,'Respostas'],[FolderTree,'Categorias'],[Star,'Favoritos'],[Upload,'Importar Word']]
const blank={title:'',category:'',content:'',tags:'',favorite:false}

export default function App(){
 const [responses,setResponses]=useState(()=>JSON.parse(localStorage.getItem('srp_responses')||'null')||seed)
 const [categories,setCategories]=useState(()=>JSON.parse(localStorage.getItem('srp_categories')||'null')||seedCats)
 const [query,setQuery]=useState(''),[active,setActive]=useState('Respostas'),[selected,setSelected]=useState(null),[mobile,setMobile]=useState(false),[toast,setToast]=useState('')
 const [form,setForm]=useState(null),[editing,setEditing]=useState(null),[newCategory,setNewCategory]=useState('')
 useEffect(()=>localStorage.setItem('srp_responses',JSON.stringify(responses)),[responses]);useEffect(()=>localStorage.setItem('srp_categories',JSON.stringify(categories)),[categories])
 const filtered=useMemo(()=>responses.filter(r=>[r.title,r.category,r.content,...r.tags].join(' ').toLowerCase().includes(query.toLowerCase())&&(active!=='Favoritos'||r.favorite)),[responses,query,active])
 const flash=t=>{setToast(t);setTimeout(()=>setToast(''),1800)}
 const copy=t=>{navigator.clipboard?.writeText(t);flash('Resposta copiada')}
 const toggleFav=id=>setResponses(v=>v.map(r=>r.id===id?{...r,favorite:!r.favorite}:r))
 const openNew=()=>{setEditing(null);setForm({...blank,category:categories[0]||''})}
 const openEdit=r=>{setEditing(r.id);setForm({...r,tags:r.tags.join(', ')})}
 const save=()=>{if(!form.title.trim()||!form.content.trim())return flash('Preencha título e resposta');const data={...form,title:form.title.trim(),content:form.content.trim(),tags:String(form.tags).split(',').map(x=>x.trim()).filter(Boolean)};if(editing)setResponses(v=>v.map(r=>r.id===editing?{...data,id:editing}:r));else setResponses(v=>[{...data,id:Date.now()},...v]);setForm(null);setEditing(null);flash(editing?'Resposta atualizada':'Resposta cadastrada')}
 const remove=id=>{if(confirm('Excluir esta resposta?')){setResponses(v=>v.filter(r=>r.id!==id));setSelected(null);flash('Resposta excluída')}}
 const addCategory=()=>{const n=newCategory.trim();if(n&&!categories.includes(n)){setCategories(v=>[...v,n].sort());setNewCategory('');flash('Categoria cadastrada')}}
 const removeCategory=c=>{if(responses.some(r=>r.category===c))return flash('Categoria possui respostas');if(confirm('Excluir esta categoria?'))setCategories(v=>v.filter(x=>x!==c))}
 const pageTitle=active==='Início'?'Visão geral':active
 return <div className="min-h-screen bg-slate-50 text-slate-900">
 <aside className={`${mobile?'translate-x-0':'-translate-x-full'} fixed inset-y-0 left-0 z-40 w-72 bg-slate-950 text-white transition-transform lg:translate-x-0`}><div className="flex h-20 items-center justify-between border-b border-white/10 px-6"><div><b>Central de Respostas</b><div className="text-xs text-slate-400">Base de conhecimento</div></div><button onClick={()=>setMobile(false)} className="lg:hidden"><X size={20}/></button></div><nav className="p-4">{nav.map(([Icon,label])=><button key={label} onClick={()=>{setActive(label);setMobile(false)}} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-4 py-3 text-sm font-medium ${active===label?'bg-blue-600':'text-slate-300 hover:bg-white/10'}`}><Icon size={19}/>{label}{label==='Respostas'&&<span className="ml-auto rounded-full bg-white/10 px-2 text-xs">{responses.length}</span>}</button>)}</nav><div className="absolute bottom-0 w-full border-t border-white/10 p-4"><button className="flex items-center gap-3 px-4 py-3 text-sm text-slate-300"><Settings size={19}/>Configurações</button><div className="mt-2 flex items-center gap-3 px-4"><div className="grid h-9 w-9 place-items-center rounded-full bg-blue-600 text-sm font-bold">RD</div><div><b className="text-sm">Raphael Dias</b><div className="text-xs text-slate-400">Administrador</div></div></div></div></aside>
 <main className="lg:pl-72"><div className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8"><div className="mb-6 flex items-center gap-3 lg:hidden"><button onClick={()=>setMobile(true)} className="rounded-xl border bg-white p-2.5"><Menu/></button><b>Central de Respostas</b></div><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 text-sm font-semibold text-blue-600">BASE DE CONHECIMENTO</div><h1 className="text-3xl font-bold">{pageTitle}</h1><p className="mt-2 text-slate-500">Organize e encontre rapidamente suas respostas de atendimento.</p></div>{!['Categorias','Importar Word'].includes(active)&&<button onClick={openNew} className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white"><Plus size={18}/>Nova resposta</button>}</header>
 {active==='Categorias'?<Categories categories={categories} responses={responses} value={newCategory} setValue={setNewCategory} add={addCategory} remove={removeCategory}/>:active==='Importar Word'?<Coming/>:<><section className="mt-7 rounded-2xl border bg-white p-4 shadow-sm"><div className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar título, conteúdo ou palavra-chave..." className="w-full rounded-xl border bg-slate-50 py-3.5 pl-12 pr-4 outline-none focus:ring-4 focus:ring-blue-100"/></div></section><div className="mt-5 flex justify-between text-sm text-slate-500"><span>{active==='Favoritos'?'Somente favoritas':'Todas as respostas'}</span><span>{filtered.length} encontradas</span></div><section className="mt-3 overflow-hidden rounded-2xl border bg-white shadow-sm">{filtered.map(r=><div key={r.id} className="grid gap-3 border-b p-5 last:border-0 md:grid-cols-[1fr_220px_150px] md:items-center"><div className="min-w-0"><div className="flex gap-2"><button onClick={()=>toggleFav(r.id)} className={r.favorite?'text-amber-500':'text-slate-300'}><Star size={18} fill={r.favorite?'currentColor':'none'}/></button><b className="truncate">{r.title}</b></div><p className="mt-1 line-clamp-1 pl-7 text-sm text-slate-500">{r.content}</p><div className="mt-2 flex gap-1 pl-7">{r.tags.map(t=><span key={t} className="rounded bg-slate-100 px-2 py-1 text-xs text-slate-500">#{t}</span>)}</div></div><div className="text-sm text-slate-500">{r.category||'Sem categoria'}</div><div className="flex md:justify-end"><IconBtn onClick={()=>copy(r.content)} icon={Copy}/><IconBtn onClick={()=>setSelected(r)} icon={Eye}/><IconBtn onClick={()=>openEdit(r)} icon={Pencil}/><IconBtn onClick={()=>remove(r.id)} icon={Trash2}/></div></div>)}{!filtered.length&&<div className="p-12 text-center text-sm text-slate-500">Nenhuma resposta encontrada.</div>}</section></>}
 </div></main>
 {form&&<Modal title={editing?'Editar resposta':'Nova resposta'} close={()=>setForm(null)}><div className="grid gap-4"><Field label="Título"><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="input"/></Field><Field label="Categoria"><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="input"><option value="">Sem categoria</option>{categories.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Palavras-chave"><input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="api, sgs, venda" className="input"/></Field><Field label="Resposta"><textarea rows="10" value={form.content} onChange={e=>setForm({...form,content:e.target.value})} className="input resize-none"/></Field><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.favorite} onChange={e=>setForm({...form,favorite:e.target.checked})}/> Marcar como favorita</label><button onClick={save} className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white"><Save size={18}/>Salvar resposta</button></div></Modal>}
 {selected&&<><div onClick={()=>setSelected(null)} className="fixed inset-0 z-40 bg-slate-950/35"/><aside className="fixed inset-y-0 right-0 z-50 flex w-full max-w-xl flex-col bg-white shadow-2xl"><div className="border-b p-6"><button onClick={()=>setSelected(null)} className="float-right rounded-lg border p-2"><X size={19}/></button><div className="text-xs font-semibold text-blue-600">{selected.category}</div><h2 className="mt-2 text-xl font-bold">{selected.title}</h2></div><div className="flex-1 overflow-auto p-6"><div className="whitespace-pre-line rounded-2xl bg-slate-50 p-5 text-sm leading-7">{selected.content}</div></div><div className="border-t p-5"><button onClick={()=>copy(selected.content)} className="flex w-full justify-center gap-2 rounded-xl bg-blue-600 p-3.5 font-semibold text-white"><Copy size={18}/>Copiar resposta</button><button onClick={()=>{setSelected(null);openEdit(selected)}} className="mt-3 flex w-full items-center justify-center text-sm font-medium">Editar <ChevronRight size={16}/></button></div></aside></>}
 {toast&&<div className="fixed bottom-5 left-1/2 z-[70] -translate-x-1/2 rounded-xl bg-slate-900 px-4 py-3 text-sm text-white shadow-xl">{toast}</div>}
 </div>
}
function IconBtn({onClick,icon:Icon}){return <button onClick={onClick} className="rounded-lg p-2.5 text-slate-500 hover:bg-slate-100"><Icon size={18}/></button>}
function Field({label,children}){return <label className="grid gap-1.5 text-sm font-medium">{label}{children}</label>}
function Modal({title,close,children}){return <><div onClick={close} className="fixed inset-0 z-50 bg-slate-950/40"/><div className="fixed left-1/2 top-1/2 z-[60] w-[calc(100%-2rem)] max-w-2xl -translate-x-1/2 -translate-y-1/2 rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b px-6 py-5"><h2 className="text-xl font-bold">{title}</h2><button onClick={close} className="rounded-lg border p-2"><X size={18}/></button></div><div className="max-h-[75vh] overflow-auto p-6">{children}</div></div></>}
function Categories({categories,responses,value,setValue,add,remove}){return <section className="mt-7"><div className="flex gap-2 rounded-2xl border bg-white p-4 shadow-sm"><input value={value} onChange={e=>setValue(e.target.value)} onKeyDown={e=>e.key==='Enter'&&add()} placeholder="Nova categoria ou Categoria › Subcategoria" className="input flex-1"/><button onClick={add} className="rounded-xl bg-blue-600 px-5 font-semibold text-white">Adicionar</button></div><div className="mt-4 overflow-hidden rounded-2xl border bg-white">{categories.map(c=><div key={c} className="flex items-center justify-between border-b p-5 last:border-0"><div><b>{c}</b><div className="mt-1 text-sm text-slate-500">{responses.filter(r=>r.category===c).length} respostas</div></div><button onClick={()=>remove(c)} className="rounded-lg p-2 text-red-500 hover:bg-red-50"><Trash2 size={18}/></button></div>)}</div></section>}
function Coming(){return <div className="mt-7 rounded-2xl border border-dashed bg-white p-12 text-center"><Upload className="mx-auto text-blue-600" size={34}/><h2 className="mt-4 text-xl font-bold">Importação do Word</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-500">A próxima etapa adicionará a leitura do arquivo .docx e a identificação dos títulos em negrito + sublinhado.</p></div>}
